# -*- coding: utf-8 -*-
"""rag_system_0203

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D5OAw6t8lzXfyEnJk2Nuwq4IcP-ts7dy
"""

!pip install -U transformers langchain langchain-community langchain-huggingface datasets
!pip install sentence-transformers chromadb accelerate bitsandbytes pdfplumber rank_bm25 gradio

from huggingface_hub import login
login("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")

# -*- coding: utf-8 -*-
import os
import time
import logging
import torch
import numpy as np
import pdfplumber
import gradio as gr
from typing import List, Dict, Optional, Any
from dataclasses import dataclass, field

# 라이브러리 임포트
from google.colab import userdata
from huggingface_hub import login
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from sentence_transformers import SentenceTransformer, CrossEncoder
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from rank_bm25 import BM25Okapi
import chromadb
from chromadb.config import Settings

# ==========================================
# 0. 환경 설정 및 인증 (Setup & Auth)
# ==========================================

# 로깅 설정
logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO
)
logger = logging.getLogger("MedicalRAG")



@dataclass
class AppConfig:
    """애플리케이션 설정 (Configuration)"""
    # Model config
    llm_model_id: str = "google/txgemma-27b-chat"
    embedding_model_id: str = "jhgan/ko-sroberta-multitask"
    reranker_model_id: str = "BAAI/bge-reranker-v2-m3"

    # Vector DB config
    collection_name: str = "medical_kb"

    # RAG Parameters
    chunk_size: int = 800
    chunk_overlap: int = 350
    initial_retrieval_k: int = 10
    final_top_k: int = 3

    # Gen Parameters
    max_new_tokens: int = 768
    temperature: float = 0.1

@dataclass
class SearchResult:
    """검색 결과 DTO"""
    text: str
    source: str
    score: float = 0.0

@dataclass
class RAGResponse:
    """RAG 응답 DTO"""
    query: str
    answer: str
    sources: List[str]

# ==========================================
# 1. 문서 처리 (Document Processing)
# ==========================================
class DocumentProcessor:
    """PDF 파싱 및 청킹 전략 패턴"""

    @staticmethod
    def _table_to_markdown(table: List[List[str]]) -> str:
        if not table or len(table) < 2: return ""
        try:
            # None 처리 및 개행 문자 제거
            sanitized_table = [['' if cell is None else str(cell).replace('\n', ' ') for cell in row] for row in table]

            # Markdown 변환
            markdown = "| " + " | ".join(sanitized_table[0]) + " |\n"
            markdown += "| " + " | ".join(["---"] * len(sanitized_table[0])) + " |\n"
            for row in sanitized_table[1:]:
                markdown += "| " + " | ".join(row) + " |\n"
            return markdown + "\n"
        except Exception as e:
            logger.warning(f"표 변환 오류: {e}")
            return ""

    @classmethod
    def process_pdf(cls, file_path: str, config: AppConfig) -> List[Dict[str, str]]:
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        logger.info(f"📄 PDF 처리 시작: {file_path}")
        docs = []

        with pdfplumber.open(file_path) as pdf:
            for i, page in enumerate(pdf.pages):
                text = page.extract_text() or ""
                tables = page.extract_tables()
                table_md = "".join([cls._table_to_markdown(t) for t in tables if t])

                content = f"{text}\n\n[표 데이터]\n{table_md}"
                docs.append(Document(
                    page_content=content,
                    metadata={"source": f"{os.path.basename(file_path)} (p.{i+1})"}
                ))

        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=config.chunk_size,
            chunk_overlap=config.chunk_overlap,
            separators=["\n\n", "\n", "|", ".", " "]
        )
        splits = text_splitter.split_documents(docs)

        logger.info(f"✅ 문서 분할 완료: {len(splits)} 청크")
        return [{"text": doc.page_content, "source": doc.metadata['source']} for doc in splits]

# ==========================================
# 2. 검색 엔진 (Retrieval Engine)
# ==========================================
class HybridRetriever:
    """Dense(Vector) + Sparse(BM25) + Reranker 검색 엔진"""

    def __init__(self, cfg: AppConfig, tokenizer):
        self.cfg = cfg
        self.tokenizer = tokenizer

        logger.info("SEARCH: 검색 엔진 초기화 중...")
        self.embed_model = SentenceTransformer(cfg.embedding_model_id)
        self.reranker = CrossEncoder(
            cfg.reranker_model_id,
            automodel_args={"torch_dtype": torch.float16},
            trust_remote_code=True
        )

        self.chroma_client = chromadb.Client(Settings(allow_reset=True))
        self.chroma_client.reset()
        self.collection = self.chroma_client.create_collection(cfg.collection_name)

        self.bm25 = None
        self.doc_map = {}

    def index_documents(self, documents: List[Dict[str, str]]):
        if not documents: return

        texts = [d['text'] for d in documents]
        ids = [f"doc_{i}" for i in range(len(texts))]

        # 1. BM25 & Map
        tokenized_corpus = [self.tokenizer.tokenize(t) for t in texts]
        self.bm25 = BM25Okapi(tokenized_corpus)

        for i, doc_id in enumerate(ids):
            self.doc_map[doc_id] = documents[i]

        # 2. Vector DB
        embeddings = self.embed_model.encode(texts, convert_to_numpy=True)
        self.collection.add(documents=texts, embeddings=embeddings.tolist(), ids=ids)
        logger.info(f"SEARCH: {len(documents)}개 문서 인덱싱 완료.")

    def search(self, query: str) -> List[SearchResult]:
        if not self.bm25: return []

        # 1. Dense Search
        q_vec = self.embed_model.encode(query).tolist()
        vec_res = self.collection.query(query_embeddings=[q_vec], n_results=self.cfg.initial_retrieval_k)
        vec_ids = vec_res['ids'][0] if vec_res['ids'] else []

        # 2. Sparse Search
        bm25_scores = self.bm25.get_scores(self.tokenizer.tokenize(query))
        top_indices = np.argsort(bm25_scores)[::-1][:self.cfg.initial_retrieval_k]
        bm25_ids = [f"doc_{i}" for i in top_indices]

        # 3. RRF Fusion
        rrf = {}
        for rank, doc_id in enumerate(vec_ids):
            rrf[doc_id] = rrf.get(doc_id, 0) + 1 / (rank + 60)
        for rank, doc_id in enumerate(bm25_ids):
            rrf[doc_id] = rrf.get(doc_id, 0) + 1 / (rank + 60)

        candidates = sorted(rrf.items(), key=lambda x: x[1], reverse=True)[:self.cfg.initial_retrieval_k]
        candidate_ids = [c[0] for c in candidates]

        # 4. Reranking
        candidate_texts = [self.doc_map[cid]['text'] for cid in candidate_ids]
        scores = self.reranker.predict([[query, t] for t in candidate_texts])

        results = []
        for cid, score in sorted(zip(candidate_ids, scores), key=lambda x: x[1], reverse=True)[:self.cfg.final_top_k]:
            doc = self.doc_map[cid]
            results.append(SearchResult(text=doc['text'], source=doc['source'], score=float(score)))

        return results

# ==========================================
# 3. 생성 엔진 (Generation Engine)
# ==========================================
class LLMGenerator:
    """LLM 답변 생성 및 후처리"""

    PROMPT_TEMPLATE = """<start_of_turn>user
당신은 '근거 중심 의학(Evidence-Based Medicine)'을 준수하는 의료 AI 전문의입니다.
아래 [검색된 문서]를 정밀하게 분석하여 질문에 답변하세요.

[검색된 문서]
{context}

[답변 작성 원칙]
1. **단계별 추론**: 질문의 의도를 파악하고, 문서에서 관련된 팩트를 찾은 뒤 답변을 구성하세요.
2. **엄격한 구분**: 문서 내의 '금기사항(Contraindications)', '주의사항(Warnings)', '권고(Indications/Target)'를 명확히 구분하세요.
3. **오해 금지**: 표 작성 시 '위험(Risk)'이라는 단어가 오해를 사지 않도록 '임상적 영향' 등으로 명확히 하세요.
4. **사실 기반**: 문서에 없는 내용은 "제공된 문서에 정보가 없습니다"라고 답하세요.
5. **출처 인용**: 답변의 근거가 되는 내용이 문서 어디에 있는지 참고하세요.


질문: {query}<end_of_turn>
<start_of_turn>model """

    def __init__(self, cfg: AppConfig):
        logger.info(f"GEN: LLM 모델 로딩 ({cfg.llm_model_id})...")
        self.cfg = cfg
        self.tokenizer = AutoTokenizer.from_pretrained(cfg.llm_model_id)
        self.model = AutoModelForCausalLM.from_pretrained(
            cfg.llm_model_id,
            quantization_config=BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_compute_dtype=torch.float16
            ),
            device_map="auto"
        )

    def generate(self, query: str, context_docs: List[SearchResult]) -> str:
        context_str = "\n\n".join([f"문서[{i+1}]: {doc.text}" for i, doc in enumerate(context_docs)])
        prompt = self.PROMPT_TEMPLATE.format(context=context_str, query=query)

        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)

        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=self.cfg.max_new_tokens,
                temperature=self.cfg.temperature,
                top_p=0.9,
                repetition_penalty=1.1,
                do_sample=True
            )

        full_text = self.tokenizer.decode(outputs[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)

        # [Refactoring Point] 답변 정제 로직을 Generator 내부로 이동 (관심사의 분리)
        return self._clean_response(full_text)

    def _clean_response(self, text: str) -> str:
        """CoT(사고 과정)를 제거하고 최종 답변만 추출"""
        if "[답변]" in text:
            return text.split("[답변]")[-1].strip()
        return text.strip()

# ==========================================
# 4. 시스템 파사드 (Facade)
# ==========================================
class MedicalRAGSystem:
    """시스템 통합 인터페이스"""

    def __init__(self):
        self.config = AppConfig()
        self.generator = LLMGenerator(self.config)
        self.retriever = HybridRetriever(self.config, self.generator.tokenizer)

    def ingest_file(self, file_path: str) -> bool:
        try:
            docs = DocumentProcessor.process_pdf(file_path, self.config)
            self.retriever.index_documents(docs)
            return True
        except Exception as e:
            logger.error(f"Ingest Error: {e}")
            return False

    def ask(self, query: str) -> RAGResponse:
        results = self.retriever.search(query)
        if not results:
            return RAGResponse(query, "관련된 문서를 찾을 수 없습니다.", [])

        answer = self.generator.generate(query, results)
        sources = list(set([r.source for r in results]))

        return RAGResponse(query, answer, sources)

# ==========================================
# 5. UI 프론트엔드 (Gradio Interface)
# ==========================================
class MedicalWebUI:
    """Gradio UI 관리 클래스"""

    def __init__(self, system: MedicalRAGSystem):
        self.system = system
        self.theme = gr.themes.Soft(
            primary_hue="teal",
            neutral_hue="slate",
            text_size="lg",
            radius_size="md"
        )

    def _adapter_ingest(self, file_obj):
        if file_obj is None: return "⚠️ Choose the file."
        if self.system.ingest_file(file_obj.name):
            return f"✅ Document analysis complete: {os.path.basename(file_obj.name)}"
        return "❌ Document analysis failure"

    def _adapter_ask(self, message, history):
        if not message: return "", history

        try:
            response = self.system.ask(message)
            answer_text = response.answer

            # 출처 포맷팅
            if response.sources:
                answer_text += "\n\n📚 Reference Document:\n" + "\n".join([f"- {s}" for s in response.sources])

        except Exception as e:
            answer_text = f"⚠️ Error: {str(e)}"

        history.append((message, answer_text))
        return "", history

    def launch(self):
        with gr.Blocks(theme=self.theme, title="Medical AI Assistant") as demo:
            gr.Markdown("# 🩺 Medical RAG Chatbot", elem_id="header")
            gr.Markdown("Medical AI Assistant based on MedGemma & RAG")
            gr.Markdown("---")

            with gr.Row():
                # 좌측 패널
                with gr.Column(scale=3, min_width=300):
                    gr.Markdown("### 📂 Document Analysis")
                    file_input = gr.File(label="PDF UPLOAD", file_types=[".pdf"], height=400)
                    status = gr.Textbox(label="Status", value="Waiting...", interactive=False)


                # 우측 채팅창
                with gr.Column(scale=7):
                    chatbot = gr.Chatbot(
                        label="Medical Consultation",
                        height=600,
                        type="tuples",
                        bubble_full_width=False,
                        avatar_images=(None, "https://cdn-icons-png.flaticon.com/512/3774/3774299.png")
                    )
                    with gr.Row():
                        msg = gr.Textbox(scale=9, show_label=False, placeholder="Enter your question...", autofocus=True)
                        btn_send = gr.Button("Send", scale=1, variant="primary")
                    gr.Markdown("*⚠️ Disclaimer: For an accurate diagnosis, please consult a physician.*")

            # 이벤트 바인딩
            file_input.upload(self._adapter_ingest, inputs=[file_input], outputs=[status])

            msg.submit(self._adapter_ask, inputs=[msg, chatbot], outputs=[msg, chatbot])
            btn_send.click(self._adapter_ask, inputs=[msg, chatbot], outputs=[msg, chatbot])

        print("🚀 웹 인터페이스를 실행합니다...")
        demo.launch(share=True, debug=True)

# ==========================================
# 6. 메인 실행 (Main Execution)
# ==========================================
if __name__ == "__main__":
    # 1. 시스템 초기화
    rag_system = MedicalRAGSystem()

    # 2. UI 실행
    ui = MedicalWebUI(rag_system)
    ui.launch()